# - name: Copy app files
#   ansible.builtin.copy:
#     src: ../../../../app
#     dest: /opt/chat-app/
#     owner: ubuntu
#     group: ubuntu
#     mode: "0755"

- name: Create .env file
  ansible.builtin.copy:
    dest: /opt/chat-app/app/.env.production
    content: |
      NODE_ENV=production
      PORT=3000
      LANGSMITH_TRACING={{ LANGSMITH_TRACING }}
      LANGSMITH_ENDPOINT={{ LANGSMITH_ENDPOINT }}
      LANGSMITH_API_KEY={{ LANGSMITH_API_KEY }}
      LANGSMITH_PROJECT={{ LANGSMITH_PROJECT }}
      GROQ_API_KEY={{ GROQ_API_KEY }}
      DEBUG=true
    mode: "0644"

- name: Add ubuntu user to the docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true

- name: Restart Docker service to apply group changes
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Deploy the application using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/chat-app/app
    build: always
    pull: always
    state: present
