apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8082'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000