- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg:
      - nginx

- name: Ensure config path exists
  become: true
  ansible.builtin.file:
    path: "{{ conf_path }}"
    state: directory
    mode: "0755"

- name: Create tls certificates
  become: true
  ansible.builtin.command: >
    openssl req -new -x509 -nodes -out {{ proj_name }}.crt
    -keyout {{ proj_name }}.key -subj '/CN={{ ansible_dns_name }}' -days 365
  args:
    chdir: "{{ conf_path }}"
    creates: "{{ conf_path }}/{{ proj_name }}.crt"
  when: tls_enabled
  notify: Restart nginx

- name: Remove the default nginx config file
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Set the nginx config file
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/chat.conf
    mode: "0640"
  notify: Restart nginx

- name: Enable the nginx config file
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/chat.conf
    dest: /etc/nginx/sites-enabled/chat.conf
    state: link
    mode: "0777"
  notify: Restart nginx
